### ISSUE TITLE
Fail to build fcitx (libintl error)

### ISSUE THREAD

**Issue by pickfire** [fcitx/fcitx#327] opened 2017-04-02 06:13 UTC
Hi, I tried building fcitx on Alpine Linux (musl-based libc) to package fcitx, I have installed the following packages:

    libexecinfo-dev libx11-dev libxkbcommon-dev libxkbfile-dev libxml2-dev iso-codes-dev enchant-dev opencc-dev cairo-dev pango-dev gobject-introspection-dev doxygen extra-cmake-modules gtk+2.0-dev gtk+3.0-dev qt-dev

When I build it with `cmake . -DCMAKE_INSTALL_PREFIX=/usr`, during `make` it returns:
```
...
-- Build files have been written to: /home/ivan/act/pkg/aports/testing/fcitx/src/fcitx-4.2.9.1
[  0%] Built target fcitx-addon-fcitx-xkbdbus--headers-1
[  0%] Built target fcitx-addon-fcitx-kimpanel-ui--headers-1
[  0%] Built target fcitx-addon-fcitx-autoeng--headers-1
[  0%] Built target fcitx-addon-fcitx-fullwidth-char--headers-1
[  0%] Linking C shared library libfcitx-utils.so
[  0%] Built target fcitx-addon-fcitx-imselector--headers-1
[  0%] Built target fcitx-addon-fcitx-remote-module--headers-1
[  0%] Built target fcitx-addon-fcitx-unicode--headers-1
[  0%] Built target fcitx-addon-fcitx-vk--headers-1
[  0%] Built target fcitx-addon-fcitx-keyboard--headers-1
CMakeFiles/fcitx-utils.dir/desktop-parse.c.o: In function `fcitx_desktop_file_load_fp':
[  0%] Built target fcitx-addon-fcitx-qw--headers-1
[  0%] Built target fcitx-addon-fcitx-table--headers-1desktop-parse.c:(.text+0x2aaf): undefined reference to `libintl_gettext'
desktop-parse.c:(.text+0x2d10): undefined reference to `libintl_gettext'
desktop-parse.c:(.text+0x2e54): undefined reference to `libintl_gettext'
desktop-parse.c:(.text+0x2f3b): undefined reference to `libintl_gettext'
desktop-parse.c:(.text+0x3055): undefined reference to `libintl_gettext'
collect2: error: ld returned 1 exit status

make[2]: *** [src/lib/fcitx-utils/CMakeFiles/fcitx-utils.dir/build.make:330: src/lib/fcitx-utils/libfcitx-utils.so.0.1] Error 1
make[1]: *** [CMakeFiles/Makefile2:798: src/lib/fcitx-utils/CMakeFiles/fcitx-utils.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  0%] Built target fcitx-addon-fcitx-xim--headers-1
[  0%] Built target fcitx-addon-fcitx-ipc--headers-1
[  0%] Built target fcitx-addon-fcitx-x11--addon--desc-1
[  0%] Built target fcitx-po-parser
make: *** [Makefile:128: all] Error 2
...
```

I tried `export LDFLAGS="$LDFLAGS -lintl"` and using `cmake . -DENABLE_PRESAGE=OFF -DENABLE_GETTEXT=OFF` but I still get the same error.

The APKBUILD can be seen at https://github.com/pickfire/aports/blob/fcitx/testing/fcitx/APKBUILD which is quite similar to Arch's PKGBUILD.

**Comment by xhebox** [comment] 2017-07-22 04:27
@pickfire you still there? it's caused by musl, you need to apply some more patches to musl and provide a fake libintl.so, contract me if you are still interested in it

**Comment by pickfire** [comment] 2017-07-22 10:13
@xhebox I guess libintl.so in alpine is broken. Can't really contract you since I am not a contractor.

**Comment by xhebox** [comment] 2017-07-22 11:56
@pickfire it's not broken, it's just not compatible with musl, i have sent an email to you. I've got fcitx for months, let's close the issue and talk in mail.

**Closed** 2017-07-22 13:59 UTC

**Comment by yangxuan8282** [comment] 2018-05-27 05:57
@pickfire 
hi, did you find solution? would mind share it, I got same issues when trying to compile fcitx on alpine.

**Comment by xhebox** [comment] 2018-05-27 07:07
@yangxuan8282 
check my build file: https://github.com/xhebox/noname-linux/blob/master/ports/fcitx/Pkgfile.

1. build fcitx need a working libexecinfo, or you just remove it like what i have done
2. you need a working gettext&intl. Either the gnu one or gettext-tiny. The latter is designed to be compatible with musl. And the former is working either in most cases, the bug is that it did not link the correct libintl automatically.

**Comment by yangxuan8282** [comment] 2018-05-27 07:42
@xhebox 
I'm using gettext-tiny, here is my APKBUILD: https://github.com/yangxuan8282/rpi-aports/blob/master/gettext-tiny/APKBUILD

as your suggest I have remove libexecinfo, this time compiling go step further, but still failed at:

``` 
Scanning dependencies of target fcitx-addon-fcitx-pinyin--addon--desc-1
[  7%] Built target fcitx-addon-fcitx-pinyin--addon--desc-1
Scanning dependencies of target py-data-download
CMakeFiles/fcitx-utils.dir/desktop-parse.c.o: In function `fcitx_desktop_file_load_fp':
desktop-parse.c:(.text+0x1b68): undefined reference to `libintl_gettext'
desktop-parse.c:(.text+0x1c88): undefined reference to `libintl_gettext'
desktop-parse.c:(.text+0x1e60): undefined reference to `libintl_gettext'
desktop-parse.c:(.text+0x1ed4): undefined reference to `libintl_gettext'
desktop-parse.c:(.text+0x21dc): undefined reference to `libintl_gettext'
collect2: error: ld returned 1 exit status
make[2]: *** [src/lib/fcitx-utils/CMakeFiles/fcitx-utils.dir/build.make:219: src/lib/fcitx-utils/libfcitx-utils.so.0.1] Error 1
make[1]: *** [CMakeFiles/Makefile2:828: src/lib/fcitx-utils/CMakeFiles/fcitx-utils.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  7%] Built target py-data-download
make: *** [Makefile:141: all] Error 2
```

**Comment by xhebox** [comment] 2018-05-27 08:06
@yangxuan8282 you have installed both gnu and tiny, right? fcitx will detect there's a gnu libintl, but as the libintl is already linked into glibc, no lintl ldflags is applied. So it failed with musl. Remove the gnu gettext, or modify Makefile to add -lintl.

**Comment by yangxuan8282** [comment] 2018-05-27 08:17
@xhebox 
actually I just installed gettext-tiny, here is my current fcitx APKBUILD: https://gist.github.com/yangxuan8282/bc25fa936fa6a0ff9fa8bb5805897820

**Comment by xhebox** [comment] 2018-05-27 08:27
@yangxuan8282 that's strange. Can you try with presage=OFF or enchant=OFF, or so, try to find which option makes the difference? Also, i am using the lastest git version gettext-tiny.

**Comment by yangxuan8282** [comment] 2018-05-27 08:45
@xhebox 
same result, neither presage=OFF or enchant=OFF not make difference

**Comment by xhebox** [comment] 2018-05-27 08:52
@yangxuan8282 i have no idea on what happened. i suggest you check if the final link command containing '-lintl' and `grep -r -H libintl source`. And here's a official guide: https://github.com/fcitx/fcitx/issues/327#issuecomment-392315496. This error really should not appear without gnu gettext..

**Comment by yangxuan8282** [comment] 2018-05-27 09:15
@xhebox 
seems something unexpected happen, although I didn't include any gnu gettext package in depends of makedepends, but I have to install `cairo-dev` as depends, otherwise the can't pass depends check of `cairo-xlib`, and `cairo-dev` depends on `glib-dev`, the `glib-dev` depends on `gettext-dev`, so as result, the gnu gettext still have been installed
do you know how to make it possible to compile with gnu gettext on musl?

**Comment by pickfire** [comment] 2018-05-27 10:51
@yangxuan8282 I have heard of a solution from @xhebox but most of it would require huge changes to other packages. I prefer @xhebox noname-linux in that case.

I recall that we need a special gettext which is different from the one in Alpine.
